packages:
  - 'packages/*'

catalog:
  typescript: 5.3.3
  tsup: 7.2.0
  '@types/node': ^18.7.20
  vite: ^7.1.7
  webpack: ^5.98.0
  '@rollup/pluginutils': ^5.3.0
  'lodash-es': ^4.17.21
  '@types/lodash-es': ^4.17.12
  